language: go
dist: trusty
sudo: false

go:
  - 1.11.x

env:
  global:
    - secure: "dBdxB+wVWCoYTHQS9VCs4DmV9Di9QFwAjDJzzlAvqhd8tlnzYsQzLu88+9h80gf6hDMOvJtlmAPn5Pjs5lJ1HF5ethmoDpOkoR76AyGoCT6l85XKXOhix4wGHLMXieOdD5LBEL+lkNeRXDFLs43hGbXp0TPAHaGhGfqXq38FePL/c0Dd45UFmGAXKo1ygDRhNiFNl4S3lFLkKdqhohYxY6Qf7jdSkq3WHMdzX3By9i+3B2ExMFo50mIMM6z7h8jHSGEMVi8aTN0HRIB15NBIhkqI2PlHeSfsInAgGgDPvVFS+aDoSUnXVajzyUDcuwdV4cqNou1r+u+8oMxUiqehrWmf2lacawnmNm/TyPhPi9g8dLLWjLLhJpnY/v281jDO82psb4sV1rldNlFG6k2BT17szcpctgaSE+psVgKo/yexQsEBO+c+d8CxeuZ/FGbXuI0W9Rmdq67ys031PyNbQFTizBOzgHagVDYbzfL4ebAsqtUj/tFez9/lKVg2tGGXIeMBCM2bps1GTzuIRUFStsOh8cXw/xGYoNCANl+yXoZYwdwUvHlOfkMUxBiy/6TJWZSOhnRdJIzVIG/F01DmbM5JCnf6oXPSMAnVB2rnwrxBbWYmh12lvjkLnIP5cIrFTzsQW1FAFfchytptj4bKaULHqGsINdU+lI392fC4Pp0="


before_install:
  - go get github.com/mattn/goveralls

install:
  - go get -u golang.org/x/lint/golint

before_script:
  - golint pkg/... cmd/...
  - go tool vet */*.go
  - test -z $(gofmt -l pkg/. cmd/.)

script:
  - $GOPATH/bin/goveralls -service=travis-ci
  - ./hack/test-go.sh
  - ./hack/build-go.sh
  - docker build -t dougbtv/whereabouts .

deploy:
  # Push images to Dockerhub on merge to master
  - provider: script
    on:
      branch: master
    script: >
      bash -c '
      docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS";
      docker push dougbtv/whereabouts:latest;
      echo done'